# Generated by Django 6.0.6 on 2026-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.CharField(max_length=100, unique=True)),
                ('messsage_id', models.IntegerField()),
                ('message_text', models.CharField(max_length=2000)),
                ('message_date', models.DateTimeField()),
                ('sender_id', models.IntegerField()),
                ('sender_fist_name', models.CharField(max_length=100, unique=True)),
                ('sender_last_name', models.CharField(max_length=100, unique=True)),
                ('is_sender_bot', models.BooleanField(default=False)),
                ('chat_id', models.IntegerField()),
                ('sender_lang_code', models.CharField(default='en', max_length=20)),
                ('chat_type', models.CharField(default='private', max_length=20)),
            ],
        ),
    ]
