# Generated by Django 6.0.6 on 2026-07-02 20:49

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_contextchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
